parameters:
    database_host: 127.0.0.1
    database_port: 3306
    database_name: medical
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: mail.emneleg.mn/
    mailer_user: support@emneleg.mn
    mailer_password: 'Mongolia123!#'
    secret: bf7ad834e7257d8679e426f56a12d1785c4dbc94
    statfolder: resources/
    localstatfolder: /resources/
    thumbsizes: 100