happy_web:
    resource: "@happyWebBundle/Controller/"
    type:     annotation
    prefix:   /

happy_security:
    resource: "@happySecurityBundle/Controller/"
    type:     annotation
    prefix:   /

happy_cms:
    resource: "@happyCmsBundle/Controller/"
    type:     annotation
    prefix:   /gombo

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"